Django2/myproject/live/urls.py
from django.urls import path
from myproject.live import views as v

app_name = 'live'

urlpatterns = [
    path('live/', v.live_list, name='live_list'),
    path('add/', v.LiveCreateView.as_view(), name='live_add'),
    path('json/', v.live_json, name='live_json')
]

Django2/myproject/live/models.py
from django.contrib.auth.models import User
from django.db import models


class Live(models.Model):
    title = models.TextField('titulo')
    guest = models.ForeignKey(
        User,
        verbose_name='convidado',
        related_name='guests',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.title

    def to_dict_json(self):
        data = {
            'pk': self.pk,
            'title': self.title,
        }
        return data

Django2/myproject/live/forms.py
from django import forms
from .models import Live


class LiveForm(forms.ModelForm):

    class Meta:
        model = Live
        fields = '__all__'

Django2/myproject/live/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import Live
from .forms import LiveForm


def live_list(request):
    lives = Live.objects.all()
    context = {'object_list': lives}
    template_name = 'live/live_list.html'
    return render(request, template_name, context)


def live_add(request):
    form = LiveForm
    context = {'form': form}
    template_name = 'live/live_form.html'
    return render(request, template_name, context)


class LiveCreateView(CreateView):
    model = Live
    template_name = 'live/live_form.html'
    form_class = LiveForm
    success_url = reverse_lazy('live:live_list')


def live_json(request):
    lives = Live.objects.all()
    data = [live.to_dict_json() for live in lives]
    return JsonResponse({'data': data})

Django2/myproject/live/templates/live/live_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Cadastrar</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button class="btn btn primary" type="submit">Salvar</button>
    </form>
{% endblock content %}

Django2/myproject/live/templates/live/live_list.html
{% extends "base.html" %}

{% block content %}

<div class="row">
  <div class="col-sm-6">
    <form action="." method="GET" class="form-inline">
      <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
      <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
    </form>
  </div>
</div>

<div class="page-header">
  <h2>Lives
    <span class="pull-right">
      <a href="{% url 'live:live_add' %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  </h2>

  {% if object_list %}

    <table class="table table-striped">
      <thead>
        <tr>
          <th class="text-center">Live</th>
          <th>Título</th>
          <th>Convidado</th>
          <th><i class="fa fa-thumbs-o-up"></i></th>
          <th><i class="fa fa-thumbs-o-down"></i></th>
          <th>Frequência</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td class="text-center">{{ object.number }}</td>
            <td>{{ object.title }}</td>
            <td>{{ object.guest.get_full_name|default:'---' }}</td>
            <td>{{ object.like }}</td>
            <td>{{ object.unlike }}</td>
            <td>{{ object.like_frequence|floatformat:3 }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% endblock content %}nt %}